### ISSUE TITLE
Error when attempting to copy _.editorconfig

### ISSUE THREAD

**Issue by LeopoldHock** [ui5-community/generator-ui5-project#9] opened 2021-05-05 07:47 UTC
During project generation I am getting an error:
`AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: D:\Users\<user>\AppData(Roaming)\npm\node_modules\generator-easy-ui5\plugin-generators\generator-ui5-project\generators\app\templates\_.editorconfig`

I have confirmed that file is definitely there at this very location. Any idea what might cause this issue? I'm on my company's notebook which has a seperate admin user (that I'm not using for my daily activities) and all that. Could this be a problem?

**Comment by IObert** [comment] 2021-06-10 12:56
Hi,

sorry for the late response - I somehow didn't get a notification from GitHub or I must have missed it.
I just checked in it works for me, can you still reproduce this error?
If so, please share the following information

## OS/version:

## Steps to reproduce the problem:

1. Step 1
2. Step 2
3. Step 3

## What is the expected result?

## What happens instead?

## Any other information? (attach screenshot if possible)

**Closed** 2021-06-21 11:09 UTC
